# Generated by Django 4.2.2 on 2023-06-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='datetime',
        ),
    ]
